name: CI
on: push
jobs:
  build:
    name: 'Run build'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install modules
        run: yarn --frozen-lockfile